# Generated by Django 3.2.9 on 2021-11-28 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_paymentselections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSelections',
        ),
    ]
