# Generated by Django 3.2.9 on 2021-12-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20211128_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_method',
            field=models.CharField(choices=[('DD', 'Giao tại 1 địa điểm'), ('TN', 'Giao tận nhà')], help_text='Bắt buộc', max_length=255, verbose_name='Lựa chọn phương thức giao hàng'),
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_name',
            field=models.CharField(help_text='Bắt buộc', max_length=255, verbose_name='Tên đơn vị giao'),
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_price',
            field=models.DecimalField(decimal_places=0, error_messages={'name': {'max_length': 'Số tiền nên nằm trong khoảng 0 đến 1.000.000'}}, help_text='Tối đa 1 000 000', max_digits=6, verbose_name='Phí giao'),
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_timeframe',
            field=models.CharField(help_text='Bắt buộc (vd: 1-2 ngày)', max_length=255, verbose_name='Thời gian giao:'),
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_window',
            field=models.CharField(help_text='Bắt buộc (vd: 9:00-21:00)', max_length=255, verbose_name='Thời điểm nhận hàng'),
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='order',
            field=models.IntegerField(default=0, help_text='Bắt buộc', verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='paymentoptions',
            name='name',
            field=models.CharField(help_text='Bắt buộc', max_length=255, verbose_name='Tên phương thức'),
        ),
    ]
