# Generated by Django 3.2.8 on 2021-10-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='user_model',
        ),
    ]
