# Generated by Django 3.2.8 on 2021-10-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/templates/static/images/Logo.png', upload_to='templates/static/images'),
        ),
    ]
