# Generated by Django 3.2.7 on 2021-11-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211111_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderCart',
            new_name='OrderItem',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
