# Generated by Django 3.2.9 on 2021-11-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20211126_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='town_city',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=False, max_length=150, verbose_name='Thành Phố/Tỉnh'),
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default=False, max_length=150, verbose_name='Họ tên người nhận'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(max_length=255, verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.AlterField(
            model_name='address',
            name='delivery_instructions',
            field=models.CharField(max_length=255, verbose_name='Ghi chú giao hàng'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Số điện thoại'),
        ),
    ]
