# Generated by Django 3.2.9 on 2021-11-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20211126_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Chưa tạo', max_length=150, verbose_name='Thành Phố/Tỉnh'),
        ),
        migrations.AlterField(
            model_name='address',
            name='delivery_instructions',
            field=models.CharField(default='Không có', max_length=255, verbose_name='Ghi chú giao hàng'),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='Chưa tạo', max_length=150, verbose_name='Họ tên người nhận'),
        ),
    ]
