# Generated by Django 3.2.9 on 2021-11-27 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20211127_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postcode',
        ),
    ]
