# Generated by Django 3.2.9 on 2021-11-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_address_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Số điện thoại nhận hàng'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='0', max_length=10, verbose_name='Số điện thoại'),
        ),
    ]
