# Generated by Django 3.2.9 on 2021-11-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_rating_rating_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
