# Generated by Django 3.2.9 on 2021-11-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/templates/static/images/defaultavatar.png', upload_to='templates/static/images'),
        ),
    ]
