# Generated by Django 3.2.9 on 2022-04-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_rating_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-created',), 'verbose_name': 'Rating', 'verbose_name_plural': 'Rating'},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='created_at',
            new_name='created',
        ),
    ]
